version: '3'

services:
   redis:
     image: redis:alpine
     restart: always
   checker:
     depends_on:
       - redis
     image: virgafox/amazon-checker-bot:latest
     ports:
       - "3000:3000"
     restart: always
     environment:
       TELEGRAM_BOT_TOKEN: <YOUR_BOT_TOKEN_HERE>
       TELEGRAM_CHAT_ID: <YOUR_CHAT_ID_HERE>
       AMAZON_PRODUCT_IDS: <PRODUCT_IDS_HERE_COMMA_SEPARATED>
       REDIS_HOST: redis
       DEBUG: checker